[package]
name = "bevy_display_compute"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.14.1"
bevy_mod_debugdump = "0.11.0"

[workspace]

members = ["examples/*"]

[workspace.dependencies]
bevy_display_compute ={ path = "./" }
